title: Eindeloos Licht
email: eindelooslicht@antrum-technologies.nl
description: Unieke lichtobjecten en designproducten van Eindeloos Licht.
baseurl: "/"
url: "https://eindelooslicht.nl"

static_form_api_key: "sf_eg7h3klah7bg2f21hnejmj3d"

collections:
  products:
    output: true
    permalink: /products/:name/

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: product
